# local path to your repo (git clone https://github.com/cocomelonc/cocomelonc.github.io)
local_repo_path: "/path/to/your/cocomelonc.github.io" # <<< CHANGE THIS TO YOUR ACTUAL PATH

# vector DB collection name
collection: "cocomelonc_blog_poc"

# gemini models
gen_model: "gemini-pro"

# which files to index (simple glob)
include_globs:
  - "_posts/**/*.md"
  - "*.md"

# optional excludes
exclude_globs:
  - ".git/**"
  - "_site/**"
  - "vendor/**"

# simple character chunking
chunk_chars: 1200
chunk_overlap: 200

# optional: used for pretty source links in answers
base_url: "https://github.com/cocomelonc/cocomelonc.github.io/blob/main/"