# path to your existing local blog repo (no cloning needed)
local_repo_path: "/home/kali/cocomelonc.github.io"
branch: "main"  # unused now, kept for compatibility

# what to include/exclude during indexing
include_globs:
  - "_posts/**/*.md"
  - "**/*.md"
exclude_globs:
  - ".git/**"
  - "_site/**"
  - "vendor/**"

# vector DB collection
collection: "cocomelonc_blog"

# ollama models
embed_model: "nomic-embed-text"   # embeddings (Ollama)
gen_model: "llama3.1:8b"          # chat LLM (Ollama); change if you prefer

# chunking
chunk_chars: 1200
chunk_overlap: 180

# markdown parsing
md:
  split_by_headings: true
  code_as_separate_chunks: true
  include_front_matter: true

# for human-friendly links back to GitHub sources (optional)
base_url: "https://github.com/cocomelonc/cocomelonc.github.io/blob/main/"
