# local path to your repo (git clone https://github.com/cocomelonc/cocomelonc.github.io)
local_repo_path: "/home/kali/cocomelonc.github.io" # <<< CHANGE THIS TO YOUR ACTUAL PATH

# vector DB collection name
collection: "cocomelonc_blog"

# gemini models
gen_model: "gemini-pro" # Changed to gemini-pro as gemini-2.5 is not a standard public model name yet

# which files to index (simple glob)
include_globs:
  - "_posts/**/*.md"
  - "*.md" # Added to catch markdown files directly in the root, if any

# optional excludes
exclude_globs:
  - ".git/**"
  - "_site/**"
  - "vendor/**"

# simple character chunking
chunk_chars: 1200
chunk_overlap: 200

# optional: used for pretty source links in answers
base_url: "https://github.com/cocomelonc/cocomelonc.github.io/blob/main/"