# local path to your repo (git clone https://github.com/cocomelonc/cocomelonc.github.io)
local_repo_path: "/home/kali/cocomelonc.github.io"

# vector DB collection name
collection: "cocomelonc_blog_poc"

# ollama models
embed_model: "nomic-embed-text"
gen_model: "llama3.1:8b"

# which files to index (simple glob)
include_globs:
  - "_posts/**/*.md"

# optional excludes
exclude_globs:
  - ".git/**"
  - "_site/**"
  - "vendor/**"

# simple character chunking
chunk_chars: 1200
chunk_overlap: 200

# optional: used for pretty source links in answers
base_url: "https://github.com/cocomelonc/cocomelonc.github.io/blob/main/"
